use std::sync::Arc;
use std::time::Instant;

use anyhow::{bail, Context, Result};
use clap::Parser;
use rand::rngs::SmallRng;
use rand::SeedableRng;
use rayon::prelude::*;
use stabstream_core::window::{OwnedSyndromeData, SyndromeWindow};
use stabstream_decoder::union_find::UnionFindDecoder;
use stabstream_decoder::{Decoder, DecoderResult};
use stabstream_dem::{DetectorErrorModel, SpacetimeGraph};
use stabstream_metrics::LogicalErrorAccumulator;
use stabstream_sim::{DemSampler, NoiseModel};

use crate::data::{write_csv, write_json, DataPoint, RunOutput};
use crate::plot::write_plot;

#[derive(Parser, Debug)]
pub struct RunArgs {
    /// DEM files, one per data point. Repeat the flag for multiple points.
    ///
    /// Each DEM represents one (distance, p_physical) operating point
    /// pre-generated by a circuit simulator at the desired error rate.
    #[arg(long = "dem", required = true, value_name = "FILE")]
    pub dems: Vec<String>,

    /// Code distances — one per --dem flag, same order.
    ///
    /// If omitted entirely, all points are labelled with distance 0.
    #[arg(long = "distance", value_name = "N")]
    pub distances: Vec<u32>,

    /// Physical error rates — one per --dem flag (inferred from DEM if omitted).
    ///
    /// Inferred value = mean probability across all DEM error mechanisms.
    #[arg(long = "p-physical", value_name = "P")]
    pub p_physical_overrides: Vec<f64>,

    /// Decoder backend.
    #[arg(long, value_enum, default_value = "union-find")]
    pub decoder: DecoderKind,

    /// Shots per (distance, p) data point.
    #[arg(long, default_value_t = 100_000)]
    pub shots: u64,

    /// Number of logical observables to track.
    #[arg(long, default_value_t = 1)]
    pub observable_count: usize,

    /// Rayon parallelism — number of threads (0 = all available CPUs).
    #[arg(long, default_value_t = 0)]
    pub threads: usize,

    /// Output file path. Extension selects format: `.csv` or `.json`.
    #[arg(long, short, default_value = "threshold.csv")]
    pub out: String,

    /// Optional SVG threshold plot.
    #[arg(long, value_name = "FILE")]
    pub plot: Option<String>,

    /// Print progress to stderr.
    #[arg(long, short)]
    pub verbose: bool,
}

#[derive(Debug, Clone, clap::ValueEnum)]
pub enum DecoderKind {
    UnionFind,
    Null,
}

impl std::fmt::Display for DecoderKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DecoderKind::UnionFind => write!(f, "union-find"),
            DecoderKind::Null => write!(f, "null"),
        }
    }
}

// ---------------------------------------------------------------------------
// Local decoder enum — avoids Box<dyn> overhead in the rayon hot path.
// ---------------------------------------------------------------------------

enum AnyDecoder {
    UnionFind(UnionFindDecoder),
    Null,
}

impl AnyDecoder {
    fn decode_window(&self, window: &SyndromeWindow) -> DecoderResult {
        match self {
            AnyDecoder::UnionFind(d) => d.decode_window(window),
            AnyDecoder::Null => DecoderResult::empty(),
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

pub fn run(args: RunArgs) -> Result<()> {
    let n = args.dems.len();

    // Validate parallel lists
    let distances: Vec<u32> = if args.distances.is_empty() {
        vec![0; n]
    } else if args.distances.len() != n {
        bail!(
            "--distance count ({}) must equal --dem count ({})",
            args.distances.len(),
            n
        );
    } else {
        args.distances.clone()
    };

    let p_overrides: Vec<Option<f64>> = if args.p_physical_overrides.is_empty() {
        vec![None; n]
    } else if args.p_physical_overrides.len() != n {
        bail!(
            "--p-physical count ({}) must equal --dem count ({})",
            args.p_physical_overrides.len(),
            n
        );
    } else {
        args.p_physical_overrides.iter().map(|&p| Some(p)).collect()
    };

    // Configure rayon thread pool size
    if args.threads > 0 {
        rayon::ThreadPoolBuilder::new()
            .num_threads(args.threads)
            .build_global()
            .ok();
    }

    if args.verbose {
        let threads = rayon::current_num_threads();
        eprintln!(
            "stabstream-threshold run  decoder={}  shots={}  threads={}  points={}",
            args.decoder, args.shots, threads, n
        );
    }

    let mut data_points: Vec<DataPoint> = Vec::with_capacity(n);

    for (i, dem_path) in args.dems.iter().enumerate() {
        let distance = distances[i];
        let p_override = p_overrides[i];

        let wall = Instant::now();
        if args.verbose {
            eprint!("[{}/{}] {} (d={}) ... ", i + 1, n, dem_path, distance);
        }

        let dem_text = std::fs::read_to_string(dem_path)
            .with_context(|| format!("reading DEM '{dem_path}'"))?;
        let dem = DetectorErrorModel::parse(&dem_text)
            .with_context(|| format!("parsing DEM '{dem_path}'"))?;

        let p_physical = p_override.unwrap_or_else(|| mean_dem_probability(&dem));
        let ancilla_count = dem.detector_count;
        let obs_count = args.observable_count;
        let shots = args.shots;
        let decoder_kind = args.decoder.clone();

        let sampler = Arc::new(DemSampler::from_dem(&dem));
        let graph = Arc::new(SpacetimeGraph::from_dem(&dem));
        let accumulator = Arc::new(LogicalErrorAccumulator::new(obs_count));

        // ---- Parallel shot loop ------------------------------------------------
        // rayon map_init: one (rng, decoder) pair per worker thread, created once.
        let acc = Arc::clone(&accumulator);
        (0..shots)
            .into_par_iter()
            .map_init(
                || {
                    let rng = SmallRng::from_entropy();
                    let dec = match decoder_kind {
                        DecoderKind::UnionFind => {
                            AnyDecoder::UnionFind(UnionFindDecoder::new(Arc::clone(&graph)))
                        }
                        DecoderKind::Null => AnyDecoder::Null,
                    };
                    (rng, dec)
                },
                |(rng, dec), _| {
                    let shot = sampler.sample(rng);
                    let window = flat_shot_to_window(&shot.detector_events, ancilla_count);
                    let result = dec.decode_window(&window);
                    acc.record(&result, shot.observable_flips);
                },
            )
            .for_each(|()| {});
        // ------------------------------------------------------------------------

        let report = accumulator.report();
        let p_l = report.mean_logical_error_rate;
        let logical_errors: u64 = report.logical_errors.iter().sum();
        let p_l_err = DataPoint::compute_stderr(p_l, shots);
        let elapsed_ms = wall.elapsed().as_millis();

        if args.verbose {
            eprintln!(
                "p_physical={:.4e}  p_l={:.4e} ± {:.2e}  ({} ms)",
                p_physical, p_l, p_l_err, elapsed_ms
            );
        }

        data_points.push(DataPoint {
            distance,
            p_physical,
            p_l,
            p_l_err,
            shots,
            logical_errors,
        });
    }

    // Write output
    if args.out.ends_with(".json") {
        let output = RunOutput {
            decoder: args.decoder.to_string(),
            shots_per_point: args.shots,
            data_points: data_points.clone(),
        };
        write_json(&args.out, &output)?;
    } else {
        write_csv(&args.out, &data_points)?;
    }
    if args.verbose || !args.out.is_empty() {
        eprintln!("Output: {}", args.out);
    }

    if let Some(ref plot_path) = args.plot {
        write_plot(plot_path, &data_points)?;
        if args.verbose {
            eprintln!("Plot:   {}", plot_path);
        }
    }

    // Print summary table to stdout
    println!(
        "{:>8}  {:>12}  {:>12}  {:>12}  {:>10}",
        "distance", "p_physical", "p_l", "±stderr", "shots"
    );
    for dp in &data_points {
        println!(
            "{:>8}  {:>12.4e}  {:>12.4e}  {:>12.4e}  {:>10}",
            dp.distance, dp.p_physical, dp.p_l, dp.p_l_err, dp.shots
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Wrap a flat shot's detector events in a single-round SyndromeWindow so the
/// UF decoder can consume them.  Node id i = detector i (no spacetime round
/// multiplier needed — the DEM already encodes spacetime structure).
fn flat_shot_to_window(detector_events: &[bool], ancilla_count: usize) -> SyndromeWindow {
    let mut window = SyndromeWindow::new(ancilla_count, 1);
    window.push_owned(OwnedSyndromeData {
        frame_id: 0,
        round: 0,
        timestamp_ns: 0,
        detector_events: detector_events.to_vec(),
        meas_results: vec![],
    });
    window
}

/// Infer p_physical from a DEM as the mean error mechanism probability.
fn mean_dem_probability(dem: &DetectorErrorModel) -> f64 {
    if dem.errors.is_empty() {
        return 0.0;
    }
    dem.errors.iter().map(|e| e.probability).sum::<f64>() / dem.errors.len() as f64
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use stabstream_dem::DetectorErrorModel;

    const REPETITION_DEM: &str = "error(0.1) D0 D1 ^ L0\n\
                                   error(0.1) D1 D2\n\
                                   error(0.1) D2 ^ L0\n\
                                   detector D0\n\
                                   detector D1\n\
                                   detector D2\n\
                                   logical_observable L0\n";

    #[test]
    fn mean_dem_probability_correct() {
        let dem = DetectorErrorModel::parse(REPETITION_DEM).unwrap();
        let p = mean_dem_probability(&dem);
        assert!((p - 0.1).abs() < 1e-12);
    }

    #[test]
    fn flat_shot_to_window_active_detectors() {
        let events = vec![true, false, true];
        let w = flat_shot_to_window(&events, 3);
        let active = w.active_detectors();
        assert!(active.contains(&0));
        assert!(!active.contains(&1));
        assert!(active.contains(&2));
    }

    #[test]
    fn run_null_decoder_zero_errors() {
        // With the null decoder, p_l should be 0 (no corrections predicted,
        // and observable_flips from sampler is also 0 when DEM has no L terms).
        let dem =
            DetectorErrorModel::parse("error(0.1) D0 D1\ndetector D0\ndetector D1\n").unwrap();
        let sampler = Arc::new(DemSampler::from_dem(&dem));
        let acc = Arc::new(LogicalErrorAccumulator::new(1));
        let acc_ref = Arc::clone(&acc);
        let n = 1000u64;
        (0..n)
            .into_par_iter()
            .map_init(
                || SmallRng::from_entropy(),
                |rng, _| {
                    let shot = sampler.sample(rng);
                    let result = DecoderResult::empty();
                    // ground truth also 0 since no L edges in DEM
                    acc_ref.record(&result, shot.observable_flips);
                },
            )
            .for_each(|()| {});
        assert_eq!(acc.total_shots(), n);
        // No L edges → ground_truth always 0, decoder always says 0 → 0 errors
        assert!((acc.logical_error_rate(0)).abs() < f64::EPSILON);
    }
}
